<a href="https://colab.research.google.com/github/ClaudiaTurner/GEOG5990M/blob/main/Final_Project_Python_GEOG5990M.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# GEOG5990M Final Assignment (Template)

Student ID number:

In [ ]:
# read in required packages

This is an example block of mardown text I want to reference <a href="#ref1">[1]</a>. I might need to add some more citations <a href="#ref2">[2]</a><a href="#ref2">[3]</a>

Data Visualisation
- Don't forget to present your final two data visualisation (one spatial and one non-spatial) and the justifications about the decisions you made whilst preparing and visualising the data.

In [2]:
import pandas as pd
# import geopandas as gpd
# import matplotlib.pyplot as plt

In [7]:
Sales_England=pd.read_csv('https://github.com/ClaudiaTurner/GEOG5990M/raw/main/DATA/Eng_sales_1995_2025_Exp.csv')

In [8]:
Sales_England.head(4)

,Residential property sales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,ONS Crown Copyright Reserved [from Nomis on 8 ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Count of sales:,Sales,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,row,Sep-96,Sep-97,Sep-98,Sep-99,Sep-00,Sep-01,Sep-02,Sep-03,Sep-04,...,Sep-16,Sep-17,Sep-18,Sep-19,Sep-20,Sep-21,Sep-22,Sep-23,Area,mnemonic

In [9]:
# Convert the years e.g Sep-96 as column titles for the dataset
## I asked Chat GPT 4o how to skip the first four rows and make row 4
##  The code will eliminate all above rows
Sales_England = pd.read_csv('https://github.com/ClaudiaTurner/GEOG5990M/raw/main/Sales_1995_2023_England_Districts_exp.csv', skiprows=4)

In [10]:
Sales_England.head(7)

,row,Sep-96,Sep-97,Sep-98,Sep-99,Sep-00,Sep-01,Sep-02,Sep-03,Sep-04,...,Sep-16,Sep-17,Sep-18,Sep-19,Sep-20,Sep-21,Sep-22,Sep-23,Area,mnemonic
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,850013.0,1047268.0,1016037.0,1084672.0,1130983.0,1133620.0,1271168.0,1153345.0,1264229.0,...,903005.0,852771.0,829715.0,803012.0,669410.0,1081660.0,787290.0,573646.0,country:England,E92000001
2,2.0,1159.0,1390.0,1405.0,1440.0,1726.0,2140.0,2359.0,2488.0,2979.0,...,1273.0,1209.0,1304.0,1235.0,1050.0,1729.0,1490.0,1103.0,ladu2023:Hartlepool,E06000001
3,3.0,1776.0,1934.0,1948.0,2055.0,2280.0,2462.0,2826.0,3016.0,3339.0,...,1822.0,1749.0,1819.0,1828.0,1528.0,2316.0,2035.0,1298.0,ladu2023:Middlesbrough,E06000002
4,4.0,1879.0,2000.0,1957.0,1986.0,2266.0,2582.0,3497.0,3390.0,3138.0,...,1824.0,1947.0,2007.0,1967.0,1636.0,2539.0,2081.0,1667.0,ladu2023:Redcar and Cleveland,E06000003
5,5.0,2670.0,3331.0,3305.0,3291.0,3978.0,4168.0,5320.0,4610.0,4471.0,...,2922.0,2959.0,3090.0,3066.0,2523.0,3826.0,3063.0,2186.0,ladu2023:Stockton-on-Tees,E06000004
6,6.0,1828.0,2178.0,2095.0,2179.0,2538.0,2770.0,3033.0,2926.0,3288.0,...,1679.0,1642.0,1602.0,1616.0,1501.0,2435.0,1885.0,1339.0,ladu2023:Darlington,E06000005

In [11]:
Sales_England.columns

Index(['row', 'Sep-96', 'Sep-97', 'Sep-98', 'Sep-99', 'Sep-00', 'Sep-01',
       'Sep-02', 'Sep-03', 'Sep-04', 'Sep-05', 'Sep-06', 'Sep-07', 'Sep-08',
       'Sep-09', 'Sep-10', 'Sep-11', 'Sep-12', 'Sep-13', 'Sep-14', 'Sep-15',
       'Sep-16', 'Sep-17', 'Sep-18', 'Sep-19', 'Sep-20', 'Sep-21', 'Sep-22',
       'Sep-23', 'Area', 'mnemonic'],
      dtype='object')

In [12]:
# Search for null values
# Explain why we have null values
Sales_England.isnull().sum()

row         1
Sep-96      1
Sep-97      1
Sep-98      1
Sep-99      1
Sep-00      1
Sep-01      1
Sep-02      1
Sep-03      1
Sep-04      1
Sep-05      1
Sep-06      1
Sep-07      1
Sep-08      1
Sep-09      1
Sep-10      1
Sep-11      1
Sep-12      1
Sep-13      1
Sep-14      1
Sep-15      1
Sep-16      1
Sep-17      1
Sep-18      1
Sep-19      1
Sep-20      1
Sep-21      1
Sep-22      1
Sep-23      1
Area        1
mnemonic    1
dtype: int64

In [13]:
# Eliminate null values
Sales_England.dropna(inplace=True)

In [18]:
Sales_England.info()  # Why does it show 30 rows? Before it wouldn't

<class 'pandas.core.frame.DataFrame'>
Index: 319 entries, 1 to 319
Data columns (total 31 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   row       319 non-null    float64
 1   Sep-96    319 non-null    float64
 2   Sep-97    319 non-null    float64
 3   Sep-98    319 non-null    float64
 4   Sep-99    319 non-null    float64
 5   Sep-00    319 non-null    float64
 6   Sep-01    319 non-null    float64
 7   Sep-02    319 non-null    float64
 8   Sep-03    319 non-null    float64
 9   Sep-04    319 non-null    float64
 10  Sep-05    319 non-null    float64
 11  Sep-06    319 non-null    float64
 12  Sep-07    319 non-null    float64
 13  Sep-08    319 non-null    float64
 14  Sep-09    319 non-null    float64
 15  Sep-10    319 non-null    float64
 16  Sep-11    319 non-null    float64
 17  Sep-12    319 non-null    float64
 18  Sep-13    319 non-null    float64
 19  Sep-14    319 non-null    float64
 20  Sep-15    319 non-null    float64
 21  Sep-16    319 non-null    float64
 22  Sep-17    319 non-null    float64
 23  Sep-18    319 non-null    float64
 24  Sep-19    319 non-null    float64
 25  Sep-20    319 non-null    float64
 26  Sep-21    319 non-null    float64
 27  Sep-22    319 non-null    float64
 28  Sep-23    319 non-null    float64
 29  Area      319 non-null    object
 30  mnemonic  319 non-null    object
dtypes: float64(29), object(2)
memory usage: 79.8+ KB

In [ ]:
# How many years does the anlysis include?
# Which years had the highest sales rate? And which district in England?
# Create new columns: Total sales per year per district and average per district
# Add histogram
# Add scatterplot
#
#
#
#
#

## References
<p><a href="add_url_here">[1]</a>Footnote citation goes here</p>
<p><a href="https://github.com/FrancescaPontin/GEOG5990">[2]</a>GEOG5990M course materials</p>
<p><a href="add_url_here">[3]</a>Citation 3</p>